### ISSUE TITLE
bug: hasteb.in links are sent with pathname `undefined` when output is too long

### ISSUE THREAD

**Issue by kyranet** [1Computer1/comp_iler#17]
Some users run `rm -rf /`, which causes this behavior (users receive https://hasteb.in/undefined).

However, a less IO-intensive way to reproduce this bug would be the following:

```javascript
'a'.repeat(10_000_000);
```

Looks like the bot is trying to read `jsonBody.code` regardless of the code (hasteb.in has a character limit):

https://github.com/1Computer1/comp_iler/blob/db995a9feaabf4887b7d9f0d16dc06519b87c741/src/listeners/messageInvalid.js#L53-L57

**Comment by papaia** [comment]
A simple check of the result should be enough, and a character limit can be set in the config.

**Comment by 1Computer1** [comment]
Output from myriad can no longer be long enough for this to happen.
