### ISSUE TITLE
Bot breaking

### ISSUE THREAD

**Issue by d-patyk** [1Computer1/comp_iler#18]
Idk, how, but this code(python) can break bot:
```py
for i in range(10**12):
  print('123' * i)
```

Result:
![image](https://user-images.githubusercontent.com/39026933/81609299-55395700-93e0-11ea-8a14-51be10ee8d03.png)

**Comment by almeidx** [comment]
From my understanding, the bot isn't doing anything. 
![image](https://user-images.githubusercontent.com/42935195/81837859-487e4580-953d-11ea-98ad-d61a8489ffc7.png)
It didn't reply to the commands.

**Comment by almeidx** [comment]
can confirm the bot is back up and running now.
