### ISSUE TITLE
Julia-evaluation broken

### ISSUE THREAD

**Issue by Splingush** [1Computer1/comp_iler#6]
Hello!

If one tries to evaluate julia-codesnippets, it breaks with the following error:

> ERROR: option `-e/--eval` is missing an argument
 
 
**Reproduction:**
>\`\`\`julia
>1+1
>\`\`\`

Maybe something along those lines will do it?

> printf %s "$1" | julia || true

> julia -E "$1" || true

Cheers!

**Comment by 1Computer1** [comment]
If problems still persist, please open it up at [Myriad](https://github.com/1Computer1/myriad)!
